#!/bin/bash

if [[ "$QT_DIR" == "" ]]; then
	echo "QT_DIR not set"
fi
if [[ "$BUILD_DIR" == "" ]]; then
	echo "BUILD_DIR not set"
fi
if [[ "$SOURCE_DIR" == "" ]]; then
	echo "SOURCE_DIR not set"
fi

set -a
APP_NAME=noson
APP_BUNDLE=Noson.app

SRC_OSX_DIR=$SOURCE_DIR/macosx
SRC_RESOURCES_DIR=$SRC_OSX_DIR/resources

BUILD_BIN_DIR=$BUILD_DIR
BUILD_BUNDLE_DIR=$BUILD_DIR/$APP_BUNDLE
BUILD_BUNDLE_CONTENTS_DIR=$BUILD_BUNDLE_DIR/Contents
BUILD_BUNDLE_APP_DIR=$BUILD_BUNDLE_DIR/Contents/MacOS
BUILD_BUNDLE_RES_DIR=$BUILD_BUNDLE_DIR/Contents/Resources
BUILD_BUNDLE_FRW_DIR=$BUILD_BUNDLE_DIR/Contents/Frameworks
BUILD_BUNDLE_PLUGIN_DIR=$BUILD_BUNDLE_DIR/Contents/PlugIns
BUILD_BUNDLE_APP_FILE=$BUILD_BUNDLE_APP_DIR/noson-gui

BUILD_BUNDLE_RES_QM_DIR=$BUILD_BUNDLE_RES_DIR/translations
BUILD_BUNDLE_RES_BIN_DIR=$BUILD_BUNDLE_CONTENTS_DIR/Tools

set +a
