TARGET = noson-silica

CONFIG += sailfishapp_qml

DISTFILES += ../gui/silica/noson.qml \
    ../gui/silica/components/CoverGrid.qml \
    ../gui/silica/components/DataFailureState.qml \
    ../gui/silica/components/Delegates/Card.qml \
    ../gui/silica/components/Delegates/DragMusicListItem.qml \
    ../gui/silica/components/Delegates/DragSelectMusicListItem.qml \
    ../gui/silica/components/Delegates/MusicListItem.qml \
    ../gui/silica/components/Delegates/SelectMusicListItem.qml \
    ../gui/silica/components/Delegates/SimpleListItem.qml \
    ../gui/silica/components/Dialog/DialogAbout.qml \
    ../gui/silica/components/Dialog/DialogAlarm.qml \
    ../gui/silica/components/Dialog/DialogApplicationSettings.qml \
    ../gui/silica/components/Dialog/DialogBase.qml \
    ../gui/silica/components/Dialog/DialogManageQueue.qml \
    ../gui/silica/components/Dialog/DialogNewPlaylist.qml \
    ../gui/silica/components/Dialog/DialogRemovePlaylist.qml \
    ../gui/silica/components/Dialog/DialogSearchMusic.qml \
    ../gui/silica/components/Dialog/DialogSelectSource.qml \
    ../gui/silica/components/Dialog/DialogServiceLabel.qml \
    ../gui/silica/components/Dialog/DialogSettings.qml \
    ../gui/silica/components/Dialog/DialogServiceLabel.qml \
    ../gui/silica/components/Dialog/DialogSleepTimer.qml \
    ../gui/silica/components/Dialog/DialogSongInfo.qml \
    ../gui/silica/components/Dialog/DialogSoundSettings.qml \
    ../gui/silica/components/Flickables/MultiSelectListView.qml \
    ../gui/silica/components/Flickables/MusicGridView.qml \
    ../gui/silica/components/Flickables/MusicListView.qml \
    ../gui/silica/components/IndexEmptyState.qml \
    ../gui/silica/components/IndexUpdateState.qml \
    ../gui/silica/components/ListItemActions/AddToFavorites.qml \
    ../gui/silica/components/ListItemActions/AddToPlaylist.qml \
    ../gui/silica/components/ListItemActions/AddToQueue.qml \
    ../gui/silica/components/ListItemActions/Remove.qml \
    ../gui/silica/components/MusicCheckBox.qml \
    ../gui/silica/components/MusicFilter.qml \
    ../gui/silica/components/MusicHeader.qml \
    ../gui/silica/components/MusicIcon.qml \
    ../gui/silica/components/MusicInfoBox.qml \
    ../gui/silica/components/MusicPage.qml \
    ../gui/silica/components/MusicRow.qml \
    ../gui/silica/components/MusicToolbar.qml \
    ../gui/silica/components/NowPlayingFullView.qml \
    ../gui/silica/components/NowPlayingSidebar.qml \
    ../gui/silica/components/NowPlayingToolbar.qml \
    ../gui/silica/components/Player.qml \
    ../gui/silica/components/PlaylistsEmptyState.qml \
    ../gui/silica/components/PopInfo.qml \
    ../gui/silica/components/Queue.qml \
    ../gui/silica/components/RenderingBubble.qml \
    ../gui/silica/components/RenderingControlerView.qml \
    ../gui/silica/components/ServiceEmptyState.qml \
    ../gui/silica/components/ServiceLogin.qml \
    ../gui/silica/components/ServiceRegistration.qml \
    ../gui/silica/components/SimpleRow.qml \
    ../gui/silica/components/StyleLight.qml \
    ../gui/silica/components/StyledSlider.qml \
    ../gui/silica/components/TrackQueue.qml \
    ../gui/silica/components/Units.qml \
    ../gui/silica/components/ZoneControls.qml \
    ../gui/silica/cover/CoverPage.qml \
    ../gui/silica/images/noson-108x108.png \
    ../gui/silica/images/noson-128x128.png \
    ../gui/silica/images/noson-86x86.png \
    ../gui/silica/images/noson.svg \
    ../gui/silica/pages/AddService.qml \
    ../gui/silica/pages/AddToPlaylist.qml \
    ../gui/silica/pages/Alarms.qml \
    ../gui/silica/pages/Albums.qml \
    ../gui/silica/pages/ArtistView.qml \
    ../gui/silica/pages/Artists.qml \
    ../gui/silica/pages/ComposerView.qml \
    ../gui/silica/pages/Composers.qml \
    ../gui/silica/pages/Favorites.qml \
    ../gui/silica/pages/Genres.qml \
    ../gui/silica/pages/Group.qml \
    ../gui/silica/pages/Index.qml \
    ../gui/silica/pages/MusicServices.qml \
    ../gui/silica/pages/NoZoneState.qml \
    ../gui/silica/pages/NowPlaying.qml \
    ../gui/silica/pages/Playlists.qml \
    ../gui/silica/pages/QueueView.qml \
    ../gui/silica/pages/Service.qml \
    ../gui/silica/pages/SongsView.qml \
    ../gui/silica/pages/ThisDevice.qml \
    ../gui/silica/pages/ThisDevice/AddToQueue.qml \
    ../gui/silica/pages/ThisDevice/Albums.qml \
    ../gui/silica/pages/ThisDevice/ArtistView.qml \
    ../gui/silica/pages/ThisDevice/Artists.qml \
    ../gui/silica/pages/ThisDevice/Genres.qml \
    ../gui/silica/pages/ThisDevice/PlayAllButton.qml \
    ../gui/silica/pages/ThisDevice/QueueAllButton.qml \
    ../gui/silica/pages/ThisDevice/ShuffleButton.qml \
    ../gui/silica/pages/ThisDevice/SongsView.qml \
    ../gui/silica/pages/Welcome.qml \
    ../gui/silica/pages/Zones.qml

RESOURCES += \
    ../gui/noson_silica.qrc
