name: build android ndk21
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - build-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run sdkmanager update
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --update
      - name: Install android platform, tools, ndk
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --install "platform-tools" "platforms;android-24" "build-tools;29.0.2" "ndk;21.4.7075529"
      - name: Dump Android NDK
        run: "ls ${ANDROID_HOME}/ndk"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'android'
          install-deps: 'true'
      - name: Dump Qt DIR
        run: |
          echo ${Qt5_DIR}
          aqt list-qt linux android --modules 5.15.2 android

      - name: Init submodules
        run: git submodule init && git submodule update
      - name: Configure manifest
        run: cp android/AndroidManifest.xml.in.ndk21 android/AndroidManifest.xml.in
      - name: Configure build
        run: "cmake -B build
                    -DCMAKE_SYSTEM_NAME=Android
                    -DCMAKE_PREFIX_PATH=${Qt5_DIR}
                    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/21.4.7075529/build/cmake/android.toolchain.cmake
                    -DCMAKE_MAKE_PROGRAM=${ANDROID_HOME}/ndk/21.4.7075529/prebuilt/linux-x86_64/bin/make
                    -DANDROID_ABI=arm64-v8a
                    -DANDROID_STL_PREFIX=llvm-libc++
                    -DANDROID_STL_SHARED_LIBRARIES=c++_shared
                    -DANDROID_SDK_MINVER=24
                    -DANDROID_SDK_TARGET=26
                    -DANDROID_NATIVE_API_LEVEL=24
                    -DQT_ANDROID_PLATFORM_LEVEL=24
                    -DQT_ANDROID_TOOL_PREFIX=aarch64-linux-android
                    -DQT_ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}
                    -DQT_ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/21.4.7075529
                    -DQT_ANDROID_QT_ROOT=${Qt5_DIR}
                    -DQT_ANDROID_SDK_BUILDTOOLS_REVISION=21.0.0
                    -DQt5_DIR=${Qt5_DIR}/lib/cmake/Qt5
                    -DQt5Core_DIR=${Qt5_DIR}/lib/cmake/Qt5Core
                    -DQt5Gui_DIR=${Qt5_DIR}/lib/cmake/Qt5Gui
                    -DQt5Qml_DIR=${Qt5_DIR}/lib/cmake/Qt5Qml
                    -DQt5Network_DIR=${Qt5_DIR}/lib/cmake/Qt5Network
                    -DQt5Quick_DIR=${Qt5_DIR}/lib/cmake/Qt5Quick
                    -DQt5QuickControls2_DIR=${Qt5_DIR}/lib/cmake/Qt5QuickControls2
                    -DQt5Xml_DIR=${Qt5_DIR}/lib/cmake/Qt5Xml
                    -DQt5Svg_DIR=${Qt5_DIR}/lib/cmake/Qt5Svg
                    -DQt5Widgets_DIR=${Qt5_DIR}/lib/cmake/Qt5Widgets
                    -DQt5QmlModels_DIR=${Qt5_DIR}/lib/cmake/Qt5QmlModels
                    -Wno-dev"
      - name: Build
        run:  cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: noson-gui-arm64-v8a-debug
          path: ${{ github.workspace }}/build/noson-gui-arm64-v8a/build/outputs/apk/debug/noson-gui-*-debug.apk
          retention-days: 5
