name: build ubuntu 24.04

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update package list
        run:  sudo apt-get update
      - name: Install software-properties-common
        run: sudo apt-get install software-properties-common
      - name: Install clang compiler and tools
        run: |
          sudo apt-get -y install clang ccache cmake pkg-config curl wget
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
              libflac-dev libflac++-dev libpulse-dev zlib1g-dev \
              libssl-dev libdbus-1-dev \
              libqt5quickwidgets5 libqt5quickcontrols2-5 libqt5qmlmodels5 libqt5qml5 \
              libqt5dbus5 libqt5svg5-dev qttools5-dev qttools5-dev-tools \
              qtdeclarative5-dev qtquickcontrols2-5-dev qtmultimedia5-dev \
              qml-module-qtquick2 qml-module-qtgraphicaleffects \
              qml-module-qtquick-layouts qml-module-qtquick-controls2 \
              qml-module-qt-labs-settings

      - name: Fetch submodules
        run: git submodule init && git submodule update
      - name: Configure build
        run: |
          cmake -B build -Wno-dev
      - name: Build
        run:  cmake --build build
      - name: Install
        run:  sudo cmake --install build
