name: build android ndk21

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java JDK for Android SDK tools
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Android SDK tools
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-24 build-tools;21.0.0 ndk;21.4.7075529"
      - name: Dump Android NDK
        run: "ls ${ANDROID_HOME}/ndk"

      - name: Install Java JDK for Android Qt build
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt/5.15.2/android
          key: ${{ runner.os }}-QtCache-5152-android
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'android'
          modules: android
          install-deps: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Dump Qt DIR
        run:  echo ${Qt5_DIR}

      - name: Fetch submodules
        run: git submodule init && git submodule update
      - name: Configure manifest
        run: cp android/AndroidManifest.xml.in.ndk21 android/AndroidManifest.xml.in
      - name: Configure build
        run: "cmake -B build
                    -DCMAKE_SYSTEM_NAME=Android
                    -DCMAKE_PREFIX_PATH=${Qt5_DIR}
                    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/21.4.7075529/build/cmake/android.toolchain.cmake
                    -DCMAKE_MAKE_PROGRAM=${ANDROID_HOME}/ndk/21.4.7075529/prebuilt/linux-x86_64/bin/make
                    -DANDROID_ABI=arm64-v8a
                    -DANDROID_STL_PREFIX=llvm-libc++
                    -DANDROID_STL_SHARED_LIBRARIES=c++_shared
                    -DANDROID_SDK_MINVER=24
                    -DANDROID_SDK_TARGET=26
                    -DANDROID_NATIVE_API_LEVEL=24
                    -DQT_ANDROID_PLATFORM_LEVEL=24
                    -DQT_ANDROID_SDK_BUILDTOOLS_REVISION=21.0.0
                    -DQT_ANDROID_TOOL_PREFIX=aarch64-linux-android
                    -DQT_ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}
                    -DQT_ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/21.4.7075529
                    -DQT_ANDROID_QT_ROOT=${Qt5_DIR}
                    -DQt5_DIR=${Qt5_DIR}/lib/cmake/Qt5
                    -DQt5Core_DIR=${Qt5_DIR}/lib/cmake/Qt5Core
                    -DQt5Gui_DIR=${Qt5_DIR}/lib/cmake/Qt5Gui
                    -DQt5Qml_DIR=${Qt5_DIR}/lib/cmake/Qt5Qml
                    -DQt5Network_DIR=${Qt5_DIR}/lib/cmake/Qt5Network
                    -DQt5Quick_DIR=${Qt5_DIR}/lib/cmake/Qt5Quick
                    -DQt5QuickControls2_DIR=${Qt5_DIR}/lib/cmake/Qt5QuickControls2
                    -DQt5Xml_DIR=${Qt5_DIR}/lib/cmake/Qt5Xml
                    -DQt5Svg_DIR=${Qt5_DIR}/lib/cmake/Qt5Svg
                    -DQt5Widgets_DIR=${Qt5_DIR}/lib/cmake/Qt5Widgets
                    -DQt5QmlModels_DIR=${Qt5_DIR}/lib/cmake/Qt5QmlModels
                    -Wno-dev"
      - name: Build
        run:  cmake --build build
